### ISSUE TITLE
image view is not proper.

### ISSUE THREAD

**Issue by jaisonka91** [MABelanger/react-html5-camera-photo#1]
Image orientation is opposite. for fixing in the view i did "transform: rotateY(180deg)" for the camera view and the thumbnail im showing in my website. But when i use native camera the view is proper so in thumbnail its rotating my image. please fix this issue in this library

**Comment by MABelanger** [comment]
Thank for reporting this issue, I embed the css `transform: rotateY(180deg)` into the component itself and i fix the dataUri to the corresponding mirror orientation. Just upgrade to the new version and it will fix your issue.
