### ISSUE TITLE
Error while taking photo on iPhone

### ISSUE THREAD

**Issue by arunkpatra** [MABelanger/react-html5-camera-photo#11]
I developed a React app and used the Camera component. It does work as intended while testing on both Windows and Mac OS (Chrome). But when I point to the site from my iPhone, it shows the following error (I have checked and ensured that Safari on iOS has been allowed access to Camera).
![image-1](https://user-images.githubusercontent.com/2806069/44309833-25ffdc80-a3ea-11e8-85d9-e0bf26777316.jpg)

Could you please help?

**Comment by MABelanger** [comment]
Witch version of ios do you use. Safari start supporting the camera with "getusermedia" since ios11 and  the camera in other browser than safari like (chrome or firefox) is not supported on iphone.

**Comment by arunkpatra** [comment]
I’m using iOS 11.4.1 and its the Safari browser I’m using.

**Comment by MABelanger** [comment]
In your parameter setting, do you allow camera ?
https://goo.gl/images/DsAieF

**Comment by arunkpatra** [comment]
Yes I have set the parameters as you have suggested and it is working now. Thank you very much.

**Comment by D063520** [comment]
Sorry but for me it is still not working ... iphone 6S, safari on localhost ... strangely your online demo is working ....

**Comment by D063520** [comment]
> In your parameter setting, do you allow camera ?
> https://goo.gl/images/DsAieF

should the option Prevent Coross-Site tracking be on or of?

**Comment by D063520** [comment]
Ok, it works, the problem was that I accessed only via HTTP and not HTTPS!
