### ISSUE TITLE
Where to find the picture in my own laptop, it is a macbook pro in this case

### ISSUE THREAD

**Issue by ManuRodgers** [MABelanger/react-html5-camera-photo#12]
Hi MABelanger, really appreciate your effort for this React-Camera component, it is awesome

**Comment by ManuRodgers** [comment]
Another question is that how to reduce the size of the picture taken by this React-Camera component?

**Comment by MABelanger** [comment]
The picture is inside the browser you need to send it to an server or 

1. Convert the dataUri to blob 
2. Save the blob to the local file : 

1) https://stackoverflow.com/questions/12168909/blob-from-dataurl

2) Maybe save the blob to the local file like this, i did not tried the code  : 
`
function saveFileFromBlob(blob) {
  let anchor = document.createElement('a');
  anchor.download = "photo.jpg";
  anchor.href = (window.webkitURL || window.URL).createObjectURL(blob);
  anchor.dataset.downloadurl = ['image/jpeg', anchor.download, anchor.href].join(':');
  anchor.click();
}
`

**Comment by MABelanger** [comment]
To reduce size, check the `sizeFactor` in PropTypes

**Comment by MABelanger** [comment]
Check out the new demo : [./src/demo/AppSaveToLocalFile.js](./src/demo/AppSaveToLocalFile.js)
