### ISSUE TITLE
shutter button not shown

### ISSUE THREAD

**Issue by sensasi-delight** [MABelanger/react-html5-camera-photo#126]
please see the code below:

[![Edit react-html5-camera-photo issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-html5-camera-photo-issue-hus7e3?fontsize=14&hidenavigation=1&theme=dark)

**Comment by framirezsandino** [comment]
Had the same issue and it was caused due to not having imported general stylesheet as shown in examples:

`...
import 'react-html5-camera-photo/build/css/index.css';
...`

Hope it helps.

**Comment by sensasi-delight** [comment]
@framirezsandino thanks man, you're my life saver 🔥
