### ISSUE TITLE
Turn off the Camera

### ISSUE THREAD

**Issue by paulgarbas** [MABelanger/react-html5-camera-photo#13]
Hi MABelanger,

how could I turn the camera off after a picture is taken?

**Comment by MABelanger** [comment]
Just remove the react-html5-camera-photo component like this demo : [/src/demo/AppWithUmountCamera.js](https://github.com/MABelanger/react-html5-camera-photo/blob/master/src/demo/AppWithUmountCamera.js)

**Comment by pntttt** [comment]
sometimes when I change component used Camera, the camera still active.
