### ISSUE TITLE
React warning

### ISSUE THREAD

**Issue by rm-hull** [MABelanger/react-html5-camera-photo#16]
I see the following warning logged by React in the browser console:

    index.js:2178 Warning: Received the string `true` for the boolean attribute `autoPlay`. Although this works, it will not work as expected if you pass the string "false". Did you mean autoPlay={true}?
        in video (created by e)
        in div (created by e)
        ...

The fix is trivial - see https://github.com/rm-hull/react-html5-camera-photo/commit/a8df72d3bbad11352b44d985dd68eb05213e499e - happy to make a PR from this commit if you agree.

**Comment by MABelanger** [comment]
Yep ! go ahead :)
