### ISSUE TITLE
Capture Button

### ISSUE THREAD

**Issue by geniuscd** [MABelanger/react-html5-camera-photo#18]
Thank you for this amazing component.
I have a question on how to trigger `<Camera>` to take a photo. it seems that the circle button is not appearing (missing css?). In addition, I need to display the taken image into another component. so what is the DataUri ? can I added it directly to an `<img src={dataUri} />` ?

I will refer to the `jslib-html5-camera-photo` documentation.

**Comment by MABelanger** [comment]
Hello,
My answers of your questions : 

Q1)  it seems that the circle button is not appearing (missing css?)
A1) Yes probably, have you imported the css like : `import 'react-html5-camera-photo/build/css/index.css'` ?

Q2) Can I added it directly to an `<img src={dataUri} />` ?
A2) Yes you can, but you can also convert the **dataUri string** to binary file on the server side and then save it in the future that it take less space than the dataUri.
