### ISSUE TITLE
how to switch camera at runtime 

### ISSUE THREAD

**Issue by ericln** [MABelanger/react-html5-camera-photo#2]
hi, 
is there a way to switch camera at run time?

**Comment by MABelanger** [comment]
For now, try to rerender the component with the new parameters in your case idealFacingMode. Like a setState() from the parent. In the new version i will add componentWillReceiveProps() that will force the new parameters (restart camera with new facingMode) without rerender the component itself.

**Comment by ericln** [comment]
sounds good thanks

**Comment by ericln** [comment]
hmm doesn't seem to work, by forcing rerender

**Comment by MABelanger** [comment]
ok thank for the info, in the next release i will add this feature inside the component.

**Comment by MABelanger** [comment]
Can you try the demo with facingMode button if it's work for you ? : https://mabelanger.github.io/react-html5-camera-photo/

I release a new version, to enable the feature, you can refer to : https://github.com/MABelanger/react-html5-camera-photo/blob/master/src/demo/AppWithDynamicProperties.js

**Comment by ericln** [comment]
yup just tried it, seems to work :)

**Comment by MABelanger** [comment]
Cool, just upgrade to the new version...
