### ISSUE TITLE
How to set height width of container

### ISSUE THREAD

**Issue by iamsaksham** [MABelanger/react-html5-camera-photo#20]
I want the camera to take the full mobile screen, same as it happens in the original camera in phone.
Is there a way to set up custom height and width

**Comment by MABelanger** [comment]
I think we can do: 
<img width="1264" alt="full_screen" src="https://user-images.githubusercontent.com/10916576/53294494-4738ef80-37b6-11e9-9424-1a770bfa21cd.png">

**Comment by MABelanger** [comment]
Hi @iamsaksham,
Sorry for the delay...
If it work, i will add props setFullScreen={true/false} it will probably do what you want.

**Comment by MABelanger** [comment]
@iamsaksham, try the new version 1.3.0 with isFullScreen props to true.

**Comment by iamsaksham** [comment]
thanks @MABelanger I'm closing this issue for now as it solves the issue

**Comment by rehan-sattar** [comment]
Hi,  the view is not responsive with the image preview. The camera resolution is showing a stretched image. Do you have any idea how to fix this issue ?

**Comment by lvidal1** [comment]
@rehan-sattar did you find a workaround?
