### ISSUE TITLE
Only secure origins are allowed

### ISSUE THREAD

**Issue by anking** [MABelanger/react-html5-camera-photo#21]
Is there a way to force-permit insecure origins (such as my devserver) to be able to test the image capture functionality?

**Comment by MABelanger** [comment]
"As per new chrome update (From Google Chrome 47), getUserMedia() is no longer supported in chrome browser over http:// (Unsecure Origin) , It will work on https:// (Secure Origin)" -> [reference](https://stackoverflow.com/questions/34165614/navigator-mediadevices-getusermedia-is-not-working-and-neither-does-webkitgetuse)

**Comment by ilhamdoanggg** [comment]
some issue with me,
so my devserver must use https to for this force-permit insecure origins
