### ISSUE TITLE
Camera showing a black screen on Safari

### ISSUE THREAD

**Issue by BvanderHoeven** [MABelanger/react-html5-camera-photo#22]
When using the standard properties in Safari the camera will show a black screen when opened, it will only show an image when you take the picture. 

This was fixed by setting the property isImageMirror to false, this removes the transform in the element's style and shows the image on Safari.

The code I use is as follows:

```
<Camera
            className="camera"
            idealFacingMode={FACING_MODES.ENVIRONMENT}
            onTakePhoto={this.onTakePhoto}
            isImageMirror={false}
          />
```

Is this a known bug to you?

**Comment by MABelanger** [comment]
which version are you using ?

**Comment by BvanderHoeven** [comment]
1.3.0
Which is the latest version right?

**Comment by MABelanger** [comment]
Can you try to downgrade to one version ie. @1.2.9 to know if is the new feature that introduce the bug ?

**Comment by MABelanger** [comment]
npm install react-html5-camera-photo@1.2.9

**Comment by MABelanger** [comment]
> 1.3.0
> Which is the latest version right?

yes
