### ISSUE TITLE
doesnt work on edge and firefox (desktop)

### ISSUE THREAD

**Issue by Alphascythian** [MABelanger/react-html5-camera-photo#25]
on firefox it gives - Camera error: Failed to allocate videosource

on edge the video isnt there, in other words it isnt displayed.
edited: managed to fix this one with polyfill.

I might be wasting your time and read something wrong, but wasnt it supported for both browsers?

**Comment by MABelanger** [comment]
Hi @Alphascythian ,
thank for your help, witch version of firefox ?

> Most commonly this happens on Windows because the webcam is already in use by another app. Firefox will throw this error on both Windows and Mac even though only on Windows processes get exclusive access to the webcam.

Maybe is the issues ? : https://stackoverflow.com/questions/42568498/notreadableerror-failed-to-allocate-videosource

**Comment by Alphascythian** [comment]
Yes, man you're fully right. Thanks for answer!

Sorry I bothered
