### ISSUE TITLE
Need silent mode

### ISSUE THREAD

**Issue by alexanderkjeldaas** [MABelanger/react-html5-camera-photo#26]
We have a use-case where we inject this on a page from a chrome extension.  In this case the page does not have a `media-src` content security policy set, so playing the click sound throws an exception.  A prop for silencing the camera would be useful.

**Comment by MABelanger** [comment]
Yes good idea.

**Comment by MABelanger** [comment]
@alexanderkjeldaas 
Check out the new version. 1.4
