### ISSUE TITLE
Countdown before taking a picture

### ISSUE THREAD

**Issue by alexanderkjeldaas** [MABelanger/react-html5-camera-photo#32]
Sometimes the user needs to fix things after pressing the capture button.  A countdown, 3...2...1 is used by Photo Booth app on OS X to facilitate this.

This could be added as an option to react-html5-camera-photo

**Comment by MABelanger** [comment]
yes it could be like delayCountdown={3}

**Comment by casulit** [comment]
> yes it could be like delayCountdown={3}

I hope that this will be implemented soon.

**Comment by MABelanger** [comment]
Right now it's not supported please refer to : https://github.com/MABelanger/react-html5-camera-photo/issues/100
