### ISSUE TITLE
Camera not Working in MI, Vivo Browser

### ISSUE THREAD

**Issue by yuvraj88** [MABelanger/react-html5-camera-photo#34]
Camera error: Cannot read property 'then' of undefined

**Comment by yuvraj88** [comment]
@MABelanger Can you please look into it

**Comment by be-grittier** [comment]
I am facing an issue in using props isFullscreen={true}
It works fine on Safari of IPhone, but in google chrome of android device, the camera screen resolution is not good.

I'd like to know whether I can fix it in the current version and how to fix this issue.

**Comment by MABelanger** [comment]
@yuvraj88 can you try to fix the issue, i don't have Vivo browser

**Comment by MABelanger** [comment]
@be-grittier yes probably the css or the resolution of the camera that does not fit in the scale of the screen.

**Comment by yuvraj88** [comment]
> @yuvraj88 can you try to fix the issue, i don't have Vivo browser

I was testing in android devices like Vivo and Mi phones their default browsers is not supporting camera. I tried to figure out that the version of their default browser is Chrome 62.
