### ISSUE TITLE
take picture in react

### ISSUE THREAD

**Issue by toeurtenh** [MABelanger/react-html5-camera-photo#35]
I follow this package to get a camera with a button to take picture with react in laravel but it's hard to get it's done as this pagekage has no much guides. any ideas?

**Comment by MABelanger** [comment]
What do you mean by this pagekage has no much guides ? The guide for laravel ?

**Comment by MABelanger** [comment]
Probably an import css missing

**Comment by sudhindrapai** [comment]
Hi,
These are imports I am using in the camera component

import React, { Component } from 'react';
import Camera from 'react-html5-camera-photo';
import 'react-html5-camera-photo/build/css/index.css';
import classes from './Camera.css';

**Comment by MABelanger** [comment]
make sure what you are using for developing support getUserMedia() but the error is supposed to be **navigator.mediaDevices.getUserMedia()** not _n.mediaDefices.getUserMedia()_
