### ISSUE TITLE
camera error: Cannot read property 'getUserMedia' of null

### ISSUE THREAD

**Issue by issnoejasso** [MABelanger/react-html5-camera-photo#36]

**Comment by issnoejasso** [comment]
on android device, shoe this message, and the canvan is not show

**Comment by currentoor** [comment]
I'm seeing the same issue when I pull the library into my project. However the demo works fine on my Android, which is strange because my code is identical.

**Comment by MABelanger** [comment]
Take a look on [WebRTC samples getUserMedia](https://webrtc.github.io/samples/src/content/getusermedia/gum/) You can get more specific tests on [WebRTC samples](https://webrtc.github.io/samples/)

**Comment by MABelanger** [comment]
I added this to the doc : https://github.com/mabelanger/react-html5-camera-photo#bug-report-issues

**Comment by MABelanger** [comment]
Take a look on [required-working-environment-for-getusermedia](https://github.com/mabelanger/react-html5-camera-photo#required-working-environment-for-getusermedia) and [bug-report-issues](https://github.com/mabelanger/react-html5-camera-photo#bug-report-issues)

If is not working, the browser do not support `getUserMedia()`

**Comment by currentoor** [comment]
My issue was not having https, I was serving assets from my laptop to my phone. Using an HTTPS tunnel made it work. Sorry, I forgot to post a comment. Thank you for updating the docs and making this library @MABelanger!
