### ISSUE TITLE
Getting "Camera Error: Invalid Constraint" on iOS (iPad)

### ISSUE THREAD

**Issue by JulsRicketti** [MABelanger/react-html5-camera-photo#40]
**Device:** iPad Air (3rd generation) (`Note: this is on Xcode's emulator, thought I'd point that out in case it matters. If this is the sole source of the issue, feel free to just close it.`)
**Operating System:** iOS 12.4
**Browser:** Safari

### Description
I am using your Camera component in the most simple way possible, I just want to display it and take the picture. So the code really does currently look something like this:

```
export function MyCameraComponent () {
  return (
      <Camera
        onTakePhoto = { (dataUri) => { console.warn('photo taken', dataUri) } }
      />
  )
}
```

This works as expected on the browser on my laptop, however it is intended to be used from an iPad.

From what I have seen in the docs since I am using Safari, this shouldn't be an issue. And it should work as expected. Is this a known issue? Have I missed a limitation parameter here?

Anyway, the component is obviously not rendered and I just get the message of `Camera error: Invalid Constraint`. 
Here is the screenshot of my component:

![Screen Shot 2019-07-30 at 5 46 20 PM](https://user-images.githubusercontent.com/886808/62167859-1c693f00-b2f2-11e9-8d0f-a0eb2093142a.png)

Thank you very much and my apologies if this is a known issue.

I should probably note that I have also tested your working demo on https://mabelanger.github.io/react-html5-camera-photo/ and do get the exact same error.

![Screen Shot 2019-07-30 at 5 53 33 PM](https://user-images.githubusercontent.com/886808/62168192-f7290080-b2f2-11e9-82b7-f959053accee.png)

**Comment by MABelanger** [comment]
Hello @JulsRicketti,
I think that the emulator do not support camera device.
