### ISSUE TITLE
react-html5-camera-photo, Only opening with selfie camera not with primary camera

### ISSUE THREAD

**Issue by nageswararao-nyros** [MABelanger/react-html5-camera-photo#41]
How to enable the primary camera using this module ?

**Comment by MABelanger** [comment]
Hi @nageswararao-nyros ,
What do you mean did you try

```js
import Camera, { FACING_MODES } from 'react-html5-camera-photo';        
<Camera
  idealFacingMode = {FACING_MODES.ENVIRONMENT}
/>
```

**Comment by nageswararao-nyros** [comment]
Hi, @MABelanger ,
Thank you. I solved an issue.

**Comment by svenvanlierde** [comment]
Hello,

On my ios device (ios 13 and browser safari) it always loads the front camera. Instead i want by default the rear.
When i change the idealFacingMode prop to FACING_MODES.ENVIRONMENT
It's still the front camara? what i'm doing wrong?

Thanks,
