### ISSUE TITLE
iOS/Safari - cannot capture square photo

### ISSUE THREAD

**Issue by dcanora** [MABelanger/react-html5-camera-photo#42]
Hello!  Trying to define a square photo - for example `idealResolution = {{width: 750, height: 750}}`.  On Android 9 it seems to work ok, but on iOS (12.4) and Safari, both preview and captured image have black bars on two sides, with a non-square image inside. The image looks fine - it's not stretched, it's just not square.

Any guidance on how to consistently define and capture square images?

(FYI for some reason on a current-gen 11" iPad Pro, using `idealResolution = {{width: 1000, height: 1000}}` throws the error, _This webpage was reloaded because a problem occurred_ but worked on a friend's iPhone. Reducing to `750` fixed the issue on the Pro.)

Thank you!

**Comment by MABelanger** [comment]
You can't if your camera don't support it. The **idealResolution** parameter is used to define the camera resolution and if the camera do not support it, it can throw an error or take the most close resolution. It's depend on the browser or/and the OS.

**Comment by dcanora** [comment]
Understood.  Thank you.
