### ISSUE TITLE
Webcam still in use after taking a picture

### ISSUE THREAD

**Issue by aditya2158** [MABelanger/react-html5-camera-photo#46]
How to release the webcam resource being utilised after onTakePicture callback? The webcam light is still on after taking the picture.

`<Camera
          onTakePhoto={dataUri => {
            this.onTakePhoto(dataUri);
          }}
          idealFacingMode={FACING_MODES.ENVIRONMENT}
          idealResolution={{ width: 400, height: 700 }}
          imageType={IMAGE_TYPES.JPG}
          imageCompression={0.97}
          isMaxResolution={false}
          isImageMirror={false}
          isSilentMode={true}
          isDisplayStartCameraError={true}
          isFullscreen={false}
          sizeFactor={1}
          onCameraStart={stream => {
            this.onCameraStart(stream);
          }}
          onCameraStop={() => {
            this.onCameraStop();
          }}
        />`

**Comment by MABelanger** [comment]
Hi @aditya2158 , you need to unmount the component you can do that with an state some thing like this 

```js 
function handleTakePhoto(dataUri){
  this.setState({ isCameraOpen:false })
}

render() {
  this.isCameraOpen && {
    <Camera onTakePhoto = {this.handleTakePhoto} />
  }
}
```

**Comment by DavidNaMills** [comment]
unmounting still doesnt work:

 ```
{!pic&&
                            <Camera
                                onTakePhoto = { (dataUri) => {takePicture(dataUri); } }
                                onCameraError = ....
/>
}
```
even if i navigate to an entirely different section, the light is still on. 
When it first loads I also get this error:
```
Error: no stream to stop!
    at index.js:578
    at new Promise (<anonymous>)
    at V.value (index.js:575)
    at index.js:204
    at new Promise (<anonymous>)
    at e.value (index.js:203)
    at e.value (index.js:165)
    at e.value (index.js:145)
    at callComponentWillReceiveProps (react-dom.development.js:14011)
    at updateClassInstance (react-dom.development.js:14221)
    at updateClassComponent (react-dom.development.js:17777)
```
then the picture loads as normal.

**Comment by MABelanger** [comment]
Hi, can you test [this code](https://github.com/MABelanger/react-html5-camera-photo#example-of-closing-the-camera-and-image-preview-after-take-a-photo) ? It's work for me, tested with chrome & firefox

**Comment by sbjovanovski** [comment]
@MABelanger I am using the example that you mentioned on how to turn remove the Camera component when the picture is taken but it seems like if I open the camera once and take a picture then it's working but if open the camera again (without refreshing the page) and I take a picture again the the camera light stays on all the time and it the solution doesn't seem to work. Any idea why?

**Comment by sbjovanovski** [comment]
> Hi, can you test [this code](https://github.com/MABelanger/react-html5-camera-photo#example-of-closing-the-camera-and-image-preview-after-take-a-photo) ? It's work for me, tested with chrome & firefox

@MABelanger  I am using the example that you mentioned on how to turn remove the Camera component when the picture is taken but it seems like if I open the camera once and take a picture then it's working but if open the camera again (without refreshing the page) and I take a picture again the the camera light stays on all the time and it the solution doesn't seem to work. Any idea why?
