### ISSUE TITLE
How to take exact snapshot? 

### ISSUE THREAD

**Issue by simistern** [MABelanger/react-html5-camera-photo#47]
Hello, 

I've been using this camera with success but I have specific requirements to lock the image into the view of the camera before saving. I notice in the demo it briefly pauses on the image being taken, but was unable to find where this works in the documentation. I have tried replacing the camera with an <img> but obviously if there was an internal mechanism for this (or even reliable way to get the dimensions) it would be greatly appreciated.

**Comment by MABelanger** [comment]
Hi @simistern take a look [here](https://github.com/MABelanger/react-html5-camera-photo#example-of-closing-the-camera-and-image-preview-after-take-a-photo) if is that what you want.
