### ISSUE TITLE
Component doesn't work on IOS 11.4.1

### ISSUE THREAD

**Issue by ron94** [MABelanger/react-html5-camera-photo#5]
On iPhone with ios 11.4.1 using Safari the component shows black blank image

**Comment by MABelanger** [comment]
Can you test if the camera work with that demo : https://mabelanger.github.io/jslib-html5-camera-photo/

If not can you test with : https://webrtchacks.github.io/WebRTC-Camera-Resolution/

**Comment by ron94** [comment]
@MABelanger None of them works

**Comment by ron94** [comment]
In this component in example it works
https://github.com/JodusNodus/react-qr-reader

**Comment by MABelanger** [comment]
Thank, Probably i need to add line 169 to 180 (// Handle different browser implementations of MediaStreams as src) https://github.com/JodusNodus/react-qr-reader/blob/master/src/index.js to support ios. I will investigate...

**Comment by MABelanger** [comment]
Fix : [https://github.com/MABelanger/react-html5-camera-photo/pull/6/commits/17e6497de174e23ffb54ddd9f1b7312a9ff45d4c](17e6497)
