### ISSUE TITLE
getting typeError cannot read property 'getUserMedia' of null on android chrome, but working fine on desktop. any workaround there?

### ISSUE THREAD

**Issue by mamta-dhaka** [MABelanger/react-html5-camera-photo#52]

**Comment by ueabu** [comment]
Getting the same issue

**Comment by MABelanger** [comment]
Which version of chrome ?
Are you using https ?

**Comment by ueabu** [comment]
I am using Safari. 
![DetectRTC  Is WebRTC Supported In Your Browser](https://user-images.githubusercontent.com/26811323/72672329-f5c4cf00-3a1d-11ea-89a6-18743ada706d.jpeg)

![React App](https://user-images.githubusercontent.com/26811323/72672331-feb5a080-3a1d-11ea-9469-780e5eda61c8.jpeg)

**Comment by MABelanger** [comment]
Do you have the same issue with demo ? : https://mabelanger.github.io/react-html5-camera-photo/

**Comment by ueabu** [comment]
Nah, the Demo works fine on mobile.

**Comment by ueabu** [comment]
I figured out what the problem was. I was not using HTTPS. I ran it and set HTTPS to true and it worked.

Thanks.
