### ISSUE TITLE
DOM exception: NotReadableError - Could not start video source

### ISSUE THREAD

**Issue by carlosalvarez91** [MABelanger/react-html5-camera-photo#54]
In a desktop browser (Chrome and Brave) works fine,
however on **android Chrome it just crashes**,
especially in a standalone PWA, sometimes it doesn't crash on a chrome tab.
It seems like it's not a problem of this package itself, I've been trying react-webcam and it throws the same error.
I've been trying to stop all tracks on init component (before opening the camera) like this:
```
navigator.getUserMedia({audio: false, video: true},
        function(stream) {
             stream.getTracks().forEach(track=>{
               track.stop()
             })
        },
        function(error){
            console.log('getUserMedia() error', error);
          }
);
```
but it still throws this exception when opening the camera
**DOM exception: NotReadableError**
I'm testing it in https context
Any solutions ?
Thanks

**Comment by MABelanger** [comment]
Hello @carlosalvarez91, why you want to stopping the video at start? What do you want to do? It's counter intuitive to me to stop the camera before using the component...

**Comment by carlosalvarez91** [comment]
Hi @MABelanger 

I found people had the same issue and sort it like this:
https://github.com/twilio/twilio-video.js/issues/325#issuecomment-397687584
https://github.com/philnash/mediadevices-camera-selection/issues/1

it also looks like its a chrome bug
https://bugs.chromium.org/p/chromium/issues/detail?id=849636
https://stackoverflow.com/a/47551322

> Most commonly this happens on Windows because the webcam is already in use by another app

about "NotReadableError":
https://blog.addpipe.com/common-getusermedia-errors/
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

> NotReadableError
Although the user granted permission to use the matching devices, a hardware error occurred at the operating system, browser, or Web page level which prevented access to the device.

**Comment by MABelanger** [comment]
yes in that case, you don't have access to the camera if other process using it. So you probably can't stop the camera in that other process.
