### ISSUE TITLE
Text document not sharp/blurred

### ISSUE THREAD

**Issue by D063520** [MABelanger/react-html5-camera-photo#55]
Hi,

I'm trying to make an App to make a photo of text documents. Unfortunately when I make the photo the image is not sharp, it is blurred. I'm using an iPhone 6S as a device. If I make the photo with the standard iOS app I do not have this problem. Any ideas?

Salut
D063520

**Comment by MABelanger** [comment]
Hello,
Probably related to the focus. It's not related to the app.
