### ISSUE TITLE
Quesion: saving the taken image

### ISSUE THREAD

**Issue by echarso** [MABelanger/react-html5-camera-photo#56]
Hi sorry for my newby question 
but how can i save the image in the dataUri
Thanks!

**Comment by echarso** [comment]
Hi again, 

I did a work arround so when a photo is taken then I store it in the state and then I reveal a download button 

<a href={ this.state.image} download>Click to download</a>

So in order to download the image captured I need to steps 
1. to click on  the camera 
2. to reveal and trigger a new button to download the image cuptured

**Comment by MABelanger** [comment]
Take a look at : [src/demo/AppSaveToLocalFile.js](https://github.com/MABelanger/react-html5-camera-photo/blob/master/src/demo/AppSaveToLocalFile.js)
