### ISSUE TITLE
when changing facing mode camera crashes

### ISSUE THREAD

**Issue by gocandra** [MABelanger/react-html5-camera-photo#57]
when i change from
 <Camera
            isImageMirror={false}
            onTakePhoto={function (dataUri) { handleDni(dataUri) }}
            isFullscreen={true}
            idealFacingMode={FACING_MODES.ENVIRONMENT}
          />

to
 <Camera
            isImageMirror={false}
            onTakePhoto={function (dataUri) { handleDni(dataUri) }}
            isFullscreen={true}
            idealFacingMode={FACING_MODES.USER}
          />

I get the following error:
NotReadableError: Could not start source

this only happens when testing on the device (android)
I imagine it's related to permissions.

**Comment by pthacker** [comment]
i am getting an inverted Rear image when starting rear camera in android

**Comment by aldialhafidzi** [comment]
> i am getting an inverted Rear image when starting rear camera in android

i have same issue..

**Comment by MABelanger** [comment]
Hello,
It fixed with the new version. Feel free to reopen it if you get the problem with the new version.
