### ISSUE TITLE
Rear camera on mobile

### ISSUE THREAD

**Issue by svenvanlierde** [MABelanger/react-html5-camera-photo#59]
Hello,

On my ios device (ios 13 and browser safari) it always loads the front camera. Instead i want by default the rear.
When i change the idealFacingMode prop to FACING_MODES.ENVIRONMENT
It's still the front camara, what i'm doing wrong?

Thanks,

**Comment by MABelanger** [comment]
try to console.log(FACING_MODES.ENVIRONMENT) it's should return "environment".
if you get "environment", we should investigate the bug with ios 13

**Comment by svenvanlierde** [comment]
Hi,

on ios and safari browser it's working now; but in chrome not ?
i always get error message :
'Camera error: TypeError undefined is not an object (evaluating 'navigator.mediaDevices.getSupportedConstraints')

Any suggestions?

Thanks

**Comment by fortis208** [comment]
We have an issue in Galaxy Note 10, we need to select the right back camera. We detected using a webcam tester that the phone has more than 1 camera at the back. 

Is there a way to select the specific back camera? 

Thank you

**Comment by Easyobj** [comment]
I have the same problem!

**Comment by mohammadsadeghforoughi** [comment]
I have the same problem !!

**Comment by MABelanger** [comment]
Hello, with IPhone, the camera is not supported with chrome and it will probably never. It's apple decision, please check the doc. Thank!
