### ISSUE TITLE
Disable onTakePhoto Image animation

### ISSUE THREAD

**Issue by SenneDirkx** [MABelanger/react-html5-camera-photo#60]
Hi,

I'm working with a keypoint tracking algorithm that expects a constant stream of base64 encoded small images. I currently have it implemented with this module but it seems to have a downside. Due to the onTakePhoto animation (the flash and (disabled) sound) I can only have 1 or 2 images per second taken. I would like this to be higher. Is there a way I can disable the animation completely?

Thanks in advance

**Comment by MABelanger** [comment]
it probably need a props like autoCaptureTimeInterval={500} this will take picture each 500ms

**Comment by khuezy** [comment]
@SenneDirkx if you're still looking for a possibly solution, you can hook onto the `onCameraStart` handler

```
function onCameraStart(stream: MediaStream) {
   const [track] = stream.getVideoTracks() // 1 video track
   const imgCapture = new ImageCapture(track)
    // wrap this in an interval 
    imgCapture.grabFrame().then(bitmap => {
      // convert bitmap to dataURL
    })
}

```

**Comment by SenneDirkx** [comment]
I solved it a different way earlier this year but I appreciate the input a lot. Didn't realize you could do it like that. Thanks!
