### ISSUE TITLE
Using inline styles

### ISSUE THREAD

**Issue by ivange94** [MABelanger/react-html5-camera-photo#64]
I noticed that this library uses global styles. So I have to do two imports 

```typescript
import Camera from 'react-html5-camera-photo';
import 'react-html5-camera-photo/build/css/index.css';
```

These global styles break other styling when used in my app. Is it possible to use inline styles so I'll have to just import the Camera component?

**Comment by FlorianRappl** [comment]
That would indeed be superb. Thanks for bringing this up @ivange94 !

Do you also accept PRs on this @MABelanger ?

**Comment by EmmanuelSkapple** [comment]
one is not resolved :/

**Comment by MABelanger** [comment]
Inside the imported css all the styles is wrapped with the css container class of `.react-html5-camera-photo` so it will not supposed to break your css. Make sure that you don't use the same css container name.

![image](https://user-images.githubusercontent.com/10916576/177655699-02c4d86a-15a6-428c-8274-08a4c8d48d56.png)
