### ISSUE TITLE
How to select specific camera?

### ISSUE THREAD

**Issue by fortis208** [MABelanger/react-html5-camera-photo#67]
We have an issue in Galaxy Note 10, we need to select the right back camera. We detected using a webcam tester that the phone has more than 1 camera at the back.

Is there a way to select the specific back camera?

Thank you

**Comment by andrevvalle** [comment]
I have the same problem!

**Comment by asyx21** [comment]
Hi, same problem for me. Is there any update?

**Comment by Borisboky** [comment]
Same here.

**Comment by MABelanger** [comment]
Hello,
Because `jslib-html5-camera-photo` has been updated, right now you can do an hack and pass a deviceId instead of idealFacingMode. In the feature release the props will be renamed to `idealCameraDevice` and `idealFacingMode` will be deprecated.

```js
    <Camera
      idealFacingMode = {deviceId}
    />
```
