### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by etayluz** [MABelanger/react-html5-camera-photo#7]
![image](https://user-images.githubusercontent.com/1825834/43478340-a517f6a2-94cb-11e8-98f4-67defab83bb9.png)

What is this error?
I just copied and pasted  the sample code from here:
https://www.npmjs.com/package/react-html5-camera-photo

**Comment by MABelanger** [comment]
Witch version do you use ?
Witch browser do you use ?
I tested the last version with create-react-app and i have no error.

**Comment by MABelanger** [comment]
Thank for reporting the issue,
I think the last upgrade will fix your issue [#8](https://github.com/MABelanger/react-html5-camera-photo/issues/8)
