### ISSUE TITLE
Permission asked multiple times (3 times) before camera launched or fail in webviews

### ISSUE THREAD

**Issue by akshayvenugopal07** [MABelanger/react-html5-camera-photo#71]
The issue is that permission popup is coming up thrice before it fails or runs in web views in fail cases it runs onError else it launches camera normally is there any reason why? It's working well in normal browsers and nice work on the library.

**Comment by scand1sk** [comment]
Apparently I have a similar bug with Safari browser on iPad. I do not have the device right now but I will try to obtain one soon.

**Comment by MABelanger** [comment]
Have you tried with the new version ? I will close this issue probably we can't do any thing about it.
