### ISSUE TITLE
Is it possible to get the camera settings?

### ISSUE THREAD

**Issue by ripern** [MABelanger/react-html5-camera-photo#78]
Is it possible somehow to get the camera settings, similar to in https://github.com/MABelanger/jslib-html5-camera-photo/blob/master/src/demo/AppSimpleVanillaJs.js#L72? Since this lib depends on jslib-html5-camera-photo I figured there might be a way that I'm not seeing. Otherwise, does it make sense to add or do you wanna keep this super simple?

The purpose would be to be able to tell whether the picture has been taken in landscape or portrait as well as the size.

**Comment by MABelanger** [comment]
Yes it could be possible, we could do a function that return the setting : getCameraSettings(settings)

**Comment by ripern** [comment]
That sounds good! Do you have time to do that?

**Comment by MABelanger** [comment]
I will close that issue but it in the dodo list.
