### ISSUE TITLE
Question: How to display rear camera of Microsoft Surface with this lib

### ISSUE THREAD

**Issue by Aarbel** [MABelanger/react-html5-camera-photo#79]
We want to use this lib to manage `<input type="file" accept="image/*" capture="camera">` problems on Microsoft Surface and Android Devices for a PWA.

Do you know which setting we should set with this lib to directly use rear camera of Microsoft Surface on Chrome Browser ?

Thanks a lot for your help !

**Comment by Aarbel** [comment]
here is what i have in my console using the userMedia api, but it doesn't take the rear one with this lib while setting idealFacingMode to "user" or "environment"

![image](https://user-images.githubusercontent.com/25119847/96854652-08ac7a00-145c-11eb-8c7a-815ee4eca5a6.png)

**Comment by MABelanger** [comment]
Hello @Aarbel ,
It will be in the next release.
Thank
