### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by chadutah** [MABelanger/react-html5-camera-photo#8]
I yarn upgraded everything but i'm still getting this error I'm using chrome. Any help would be amazing!

**Comment by MABelanger** [comment]
Can you send me your packages.json, because i can't reproduce the bug.

**Comment by chadutah** [comment]
{
  "name": "mern",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "start": "if-env NODE_ENV=production && npm run start:prod || npm run start:dev",
    "start:prod": "node server.js",
    "start:dev": "concurrently \"nodemon --ignore 'client/*'\" \"npm run client\"",
    "client": "cd client && npm run start",
    "seed": "node scripts/seedDB.js && node scripts/seedsGamesDB.js",
    "install": "cd client && yarn install",
    "build": "cd client && npm run build",
    "heroku-postbuild": "npm run build"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "concurrently": "^3.5.0",
    "nodemon": "^1.11.0"
  },
  "dependencies": {
    "ajax": "^0.0.4",
    "axios": "^0.18.0",
    "bcrypt": "^3.0.0",
    "body-parser": "^1.17.2",
    "cloudinary": "^1.11.0",
    "connect-mongo": "^2.0.1",
    "expo": "^29.0.0",
    "express": "^4.15.4",
    "express-session": "^1.15.6",
    "if-env": "^1.0.4",
    "jquery": "^3.3.1",
    "mongoose": "^5.0.17",
    "morgan": "^1.9.0",
    "passport": "^0.4.0",
    "passport-local": "^1.0.0",
    "react-awesome-modal": "^2.0.3",
    "react-bootstrap": "^0.32.1",
    "react-camera": "^0.1.3",
    "react-facebook-auth": "^1.4.0",
    "react-facebook-login": "^4.0.1",
    "react-html5-camera-photo": "^1.2.3-beta.0",
    "react-native": "^0.56.0",
    "react-table": "^6.8.6",
    "reactstrap": "^6.2.0",
    "shuffle-array": "^1.0.1",
    "whatwg-fetch": "^2.0.4"
  }
}

**Comment by chadutah** [comment]
it works when i fist load the component, then i'm sending the picture to cloudinary which also works then i take the url from cloudinary and send it up to the kairos api and with the response from kairos i trigger a function and a modal and this is when it breaks and gives me that error

**Comment by chadutah** [comment]
I just changed my modals to alerts everything works fine

**Comment by chadutah** [comment]
so the issue is when you try to put a modal in the same div as the camera

**Comment by MABelanger** [comment]
Maybe is when the component is unmonted, the alert keep the component mounted.

**Comment by MABelanger** [comment]
Can you see in the stack of error something ?

**Comment by MABelanger** [comment]
Ok i found a way to reproduce the bug.
I will update a new version ;) I will notify you when i will do

**Comment by chadutah** [comment]
thank you so much!

**Comment by MABelanger** [comment]
Ok thank for reporting the issue !
You can upgrade to the fixed version react-html5-camera-photo@1.2.4-beta.0
