### ISSUE TITLE
How to use a particular deviceId with this library ?

### ISSUE THREAD

**Issue by Aarbel** [MABelanger/react-html5-camera-photo#81]
I want to choose the device ID to use as videoinput, is there a way to do it with this lib ?

**Comment by MABelanger** [comment]
No, this app is hight level abstraction of getUserMedia()

**Comment by MABelanger** [comment]
What do you want to do ? you have more than 2 camera on your phone ?

**Comment by Aarbel** [comment]
@MABelanger i think the problem comes from your secondary lib `jslib-html5-camera-photo` which doesn't allow to pass a deviceId.

My problem is that "environment" camera isn't equivalent to rear or back camera on many devices. (for example "environment" shows front camera on Microsoft Surface and some Android Devices). 

I think it could be really great to create a public lib to use front or rear camera on most of the devices, function of accessibles devices listed by getUserMedia();

Example of my code today (using low lever getUserMedia api, i'm not using your 2 libraries because of this issue):
```JS
    navigator.mediaDevices.enumerateDevices().then((mediaDevices) => {
      const videoDevices = mediaDevices.filter(
        (device) => device.kind === "videoinput"
      );
      console.info("videoDevices: ", videoDevices);

      /* We have to check manually which is the right device camera, because there's not
         standard library to manage that, especially for weird devices like Microsoft Surfaces */
      const backCameraDevice = videoDevices.find(
        (d) =>
          d.label.toLowerCase().includes("back") ||
          d.label.toLowerCase().includes("rear")
      );
      const backCameraId = backCameraDevice && backCameraDevice.deviceId;

      const frontCameraDevice = videoDevices.find(
        (d) => d.deviceId !== backCameraId
      );
      const frontCameraId = frontCameraDevice && frontCameraDevice.deviceId;

      // console.log("frontCameraId :>> ", frontCameraId);
      // console.log("backCameraId :>> ", backCameraId);

      const constraints = {
        audio: false,
        video: {
          deviceId: backCameraId || frontCameraId,
        },
      };

      navigator.mediaDevices
        .getUserMedia(constraints)
        .then(this.handleSuccessGetUserMedia)
        .catch(this.handleErrorGetUserMedia);
    });
```

**Comment by the-simian** [comment]
This is useful when there are multiple USB devices with cameras on a desktop as well, such as with a remote-learning document camera that is separate from a camera used for streaming your face. Its easy enough to get the list of devices, I just want to tell this component exactly which device Id to target optionally

```js
 async function getCameraList() {
      if(!navigator.mediaDevices) return [];
      var deviceList = await navigator.mediaDevices.enumerateDevices();
      var cameras = deviceList.filter((device) => device.kind == 'videoinput'));
      /*
      cameras: this is a list of cameras each possessing a readable name and a device Id. 
      I want to target one in situations with more than one camera
      */
  }
```

**Comment by Aarbel** [comment]
Just had a surprise on wkwebview on Android:

wkwebview doesn't handle well mediaDevices `labels`, so hard to get a backCamera Id

So i had to do that to directly open back camera:

```JS
      const constraints = {
        audio: false,
        video: {
          facingMode: "environment",
          deviceId: backCameraId,
        },
      };
```

**Comment by MABelanger** [comment]
Hello,
Because `jslib-html5-camera-photo` has been updated, right now you can do an hack and pass a deviceId instead of idealFacingMode. In the feature release the props will be renamed to `idealCameraDevice` and `idealFacingMode` will be deprecated.

```js
    <Camera
      idealFacingMode = {deviceId}
    />
```

**Comment by Aarbel** [comment]
Ref https://github.com/MABelanger/react-html5-camera-photo/issues/79
