### ISSUE TITLE
onTakePhoto dosen't work using mobile phone

### ISSUE THREAD

**Issue by MahdiElAbed** [MABelanger/react-html5-camera-photo#82]
I am using react-html5-camera-photo in my PWA application. Actually, it works fine when i run my app using my pc on localhost, however, i get an error when press the take photo button when running the app on my phone :" camera error: TypeError: navigator.mediaDevices.getSupportedConstraints is not a function. I am stuck at this level, any idea how should i proceed please !
Thank you.

**Comment by Borisboky** [comment]
The same problem here.

**Comment by MABelanger** [comment]
Does the [demo](https://mabelanger.github.io/react-html5-camera-photo/) work on your phone ?

**Comment by Borisboky** [comment]
@MABelanger 

The demo works.

**Comment by Borisboky** [comment]
@MABelanger 

But the problem is when I use `idealFacingMode={FACING_MODES.ENVIRONMENT}`. If I use it without that, it works fine, but I need back camera.

**Comment by MABelanger** [comment]
Which browser do you use ? Check here on [DetectRTC](https://www.webrtc-experiment.com/DetectRTC/)

**Comment by Borisboky** [comment]
@MABelanger Its Chrome version 86.,.4240.185 and Android version 10.

**Comment by MABelanger** [comment]
Probably new android has two cameras as environment so`idealFacingMode={FACING_MODES.ENVIRONMENT}` probably don't work. I really need your setting of the phone to find a solution. Can you paste the image of [DetectRTC](https://www.webrtc-experiment.com/DetectRTC/). Click on open as image, save it and upload it here it will be appreciate.

Thank

**Comment by MABelanger** [comment]
@Borisboky  Are you able to see environment camera with : [jslib-html5-camera-photo demo](https://mabelanger.github.io/jslib-html5-camera-photo/) ?

**Comment by khuezy** [comment]
@MahdiElAbed @Borisboky the browser `mediaDevices` is only supported on localhost and secured sites (https). When testing your site on your phone, are you using a secured connection or localhost? Using your intranet IP 192.168.x.x will result in the error "getSupportedContraint of undefined"

To test your mobile device locally, you can plug it into your USB and enable USB debugging. Launch chrome on phone and desktop. Visit `brave://inspect/#devices` or `chrome://inspect/#devices` on your desktop and configure your port forwarding.

You can visit `localhost` on your phone and it'll be forwarded to your computer's server where you can access the `mediaDevices` API.

**Comment by toduyen** [comment]
The program running on my phone cannot use the rear camera.  My phone runs on Android 10 operating system @MABelanger . this is check here DetectedRTC
![Screenshot_20211010-223157_Messenger](https://user-images.githubusercontent.com/62172265/136703303-e996d21e-0f22-48d1-9198-116a4a814b29.jpg)

**Comment by MABelanger** [comment]
Hi,
Sorry for the late reply, 
Can you try with the new version ?
I will close that issue,
Thank !
