### ISSUE TITLE
camera cant support on safari IOS mobile

### ISSUE THREAD

**Issue by ilhamdoanggg** [MABelanger/react-html5-camera-photo#88]
cant help for fix this issue 

![Screen Shot 2021-01-20 at 14 13 01](https://user-images.githubusercontent.com/9218660/105140052-be559a80-5b29-11eb-8ffe-7469e3812568.png)

thanks you

**Comment by MABelanger** [comment]
It's probably your constraints resolution in the parameter that do not supported by your device. Try to remove the constraints resolution or put another one. The code has changed a lot since, please retry with new version. Thank !
