### ISSUE TITLE
onTakePhoto doesn't run on mobile 

### ISSUE THREAD

**Issue by chadutah** [MABelanger/react-html5-camera-photo#9]
everything works just fine when i take pictures from my computer but when i try from my phone, same website it takes a picture but doesn't run any of the onTakePhoto function. Do you have any idea why this might be?

**Comment by MABelanger** [comment]
Does the animation of the button is activated when you click on the button ?
Do you hear a click ?
Maybe put an alert inside your onTakePhoto(dataUri) fct

**Comment by chadutah** [comment]
yes it makes the click sound

**Comment by MABelanger** [comment]
Does it freeze the image for 1 second with a white flash ?

**Comment by chadutah** [comment]
yes, I added an alert the alert fires too 
it just won't run the cloudinary.uploader.upload()

**Comment by MABelanger** [comment]
Maybe put the alert into the .then() promise of the cloudinary.uploader.upload() It seem not related to the react-html5-camera-photo

**Comment by chadutah** [comment]
now i'm even more confused the alert fires in the callback but nothing is uploaded to cloudinary

**Comment by chadutah** [comment]
is the dataUri different for mobile? because it works just fine on desktop

**Comment by MABelanger** [comment]
you can do alert(dataUri.length)

**Comment by chadutah** [comment]
ok i think its a problem with cloudinary you can close this issue thanks for everything!
