### ISSUE TITLE
Where The taken Img is Saved means at which Dir Its Save

### ISSUE THREAD

**Issue by karthik2342323** [MABelanger/react-html5-camera-photo#97]
Needed an Taken Photo to save or Download Option to User so They can Access It

**Comment by MABelanger** [comment]
Hello @karthik2342323 ,
i get a example inside the demo folder how to do it.
[src/demo/AppSaveToLocalFile.js](https://github.com/MABelanger/react-html5-camera-photo/blob/master/src/demo/AppSaveToLocalFile.js)
