### ISSUE TITLE
Multiple Re-Renders cause no video being shown

### ISSUE THREAD

**Issue by MGreif** [MABelanger/react-html5-camera-photo#99]
Dear Community and MABelanger,

while testing out the functionality of this module ive encountered a few things i wanna talk about:

Due to the redux state changes, the `<Camera ... />` component rerenders quite often. This causes the Hook to falsely clear the current mediaStream so no video is shown. Note: Taking a picture does not change anything at all. Only a complete Restart of the Client will fix this.

I thought about replacing the `useState` hook, used to initialise the mediaStream local-state, with the `useRef` hook. 

The useRef hook works synchronously so the state-changes caused by the rerenders will happen instantly while the useState hook works asynchronously so the state-changes wont be updated instantly. Using the useRef hook could prevent confusions with multiple re-renders.

What do you think?

**Comment by MABelanger** [comment]
Hi @MGreif ,
Sorry for late reply but here is what happen. The `<Camera .../>` is connected to the camera when the component is mount and stop the camera when it' unmount. So in any ways, we want to do cycle start/stop the camera as little as possible. So even with the useRef, in that hook, the problem will still there. So you need to avoid multiple cycle mount/umount of the `<Camera/>`. I will close that issue Thank !
